services:
  api:
    build: ./Backend/API/
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - grafana

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana en el puerto 3000
    networks:
      - backend
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Usuario admin
      - GF_SECURITY_ADMIN_PASSWORD=sopes1  # Contraseña
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource # Plugin de Infinity Datasource
    volumes:
      - grafana_data:/var/lib/grafana  # Persistencia de Grafana
      - ./Backend/Grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml  # Configuración de dashboards
      - ./Backend/Grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml  # Nuevo archivo de configuración
      - ./Backend/Grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json  # Dashboard JSON


volumes:
  grafana_data:

networks:
  backend:
    driver: bridge
