apiVersion: 1
datasources:
  - name: valkey
    type: "redis-datasource"  # UID del plugin instalado
    access: "proxy"
    url: "redis://valkey:6379"  # URL del backend de datos
    isDefault: true
    jsonData:
      authType: "none"  # Configuración sin autenticación (ajusta si es necesario)
