apiVersion: 1
datasources:
  - name: valkey-datasource
    type: "redis-datasource"  # UID del plugin instalado
    access: "proxy"
    url: "redis://sopesp2-service-valkey:6379"  # URL del backend de datos
    isDefault: true
    jsonData:
      authType: "none"  # Configuraci贸n sin autenticaci贸n (ajusta si es necesario)
  - name: redis-datasource
    type: "redis-datasource"  # UID del plugin instalado
    access: "proxy"
    url: "redis://sopesp2-service-redis:6380"  # URL del backend de datos
    jsonData:
      authType: "none"  # Configuraci贸n sin autenticaci贸n (ajusta si es necesario)