apiVersion: apps/v1
kind: Deployment
metadata:
  name: sopesp2-deployment-consumer-kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sopesp2-consumer-kafka
  template:
    metadata:
      labels:
        app: sopesp2-consumer-kafka
    spec:
      containers:
        - name: sopesp2-consumer-kafka
          image: 34.46.182.53.nip.io/smillermp/sopesp2-consumer-kafka:1.0 
          imagePullPolicy: Always
          env:
            - name: KAFKA_SERVER
              value: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: NO_GOROUTINES
              value: "15"
            - name: REDIS_SERVER
              value: "sopesp2-service-redis:6380"
          resources:
            requests:
              cpu: "80m"
              memory: "128Mi"
            limits:
              cpu: "150m"
              memory: "256Mi"