apiVersion: apps/v1
kind: Deployment
metadata:
  name: sopesp2-deployment-go-grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sopesp2-go-grpc
  template:
    metadata:
      labels:
        app: sopesp2-go-grpc
    spec:
      containers:
        - name: sopesp2-go-api-grpc
          image: smillermp/sopesp2-go-api-grpc:1.0 
          imagePullPolicy: Always
          ports:
            - containerPort: 8010
          env:
            - name: API_PORT
              value: "8010"
            - name: GRPC_SERVER_KAFKA
              value: "sopesp2-service-grpc-server-kafka:50051"
            - name: GRPC_SERVER_RABBITMQ
              value: "sopesp2-service-grpc-server-rabbitmq:50052"

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"