apiVersion: apps/v1
kind: Deployment
metadata:
  name: sopesp2-deployment-rust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sopesp2-service-rust
  template:
    metadata:
      labels:
        app: sopesp2-service-rust
    spec:
      containers:
        - name: sopesp2-rust
          image: 34.46.182.53.nip.io/smillermp/sopesp2-rust-api:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: API_PORT
              value: "8000"
            - name: GOLANG_API_URL
              value: "http://sopesp2-service-go-grpc:8010/weather" # URL del servicio gRPC de Go
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"