apiVersion: apps/v1
kind: Deployment
metadata:
  name: sopesp2-deployment-valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: bitnami/valkey:8.0
          ports:
            - containerPort: 6379   
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            # - name: VALKEY_DISABLE_COMMANDS
            #   value: "FLUSHDB,FLUSHALL"
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"