apiVersion: v1
kind: Service
metadata:
  name: sopesp2-service-valkey
spec:
  selector:
    app: valkey
  ports:
    - name: management
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 31010     # exponer el puerto 31010 para el servicio
  type: NodePort
