apiVersion: v1
kind: Service
metadata:
  name: sopesp2-service-rust
spec:
  selector:
    app: sopesp2-service-rust
  ports:
    - protocol: TCP
      port: 80          # puesto del ingress
      targetPort: 8000 # El puerto del contenedor
  type: ClusterIP