apiVersion: v1
kind: Service
metadata:
  name: sopesp2-service-go-grpc
spec:
  selector:
    app: sopesp2
  ports:
    - protocol: TCP
      port: 8010          # El puerto del servicio en el clúster
      targetPort: 8010    # El puerto del contenedor
  type: ClusterIP