apiVersion: v1
kind: Service
metadata:
  name: sopesp2-service-grpc-server-rabbitmq
spec:
  selector:
    app: sopesp2
  ports:
    - protocol: TCP
      port: 50052          # El puerto del servicio en el clúster
      targetPort: 50052    # El puerto del contenedor
  type: ClusterIP