services:
  # Servicios de LOCUST
  master:
    image: locustio/locust
    networks:
      - kuber-net
    ports:
      - "8089:8089"
    volumes:
      - ./Backend/Locust/locustfile.py:/mnt/locust/locustfile.py  
    working_dir: /mnt/locust  # El directorio de trabajo es /mnt/locust
    command: -f /mnt/locust/locustfile.py --users 10 --master -H http://api_rust:8000

  
  worker:
    image: locustio/locust
    networks:
      - kuber-net
    volumes:
      - ./Backend/Locust/data:/mnt/locust/data  
      - ./Backend/Locust/locustfile.py:/mnt/locust/locustfile.py 
    working_dir: /mnt/locust  
    command: -f /mnt/locust/locustfile.py --worker --master-host master

  # API_rust
  api_rust:
    build: ./Backend/Rust/API
    ports:
      - "8000:8000"
    networks:
      - kuber-net

  # API_golang
  api_golang:
    build: ./Backend/Golang/API
    ports:
      - "8010:8010"
    networks:
      - kuber-net
    
networks:
  kuber-net:
    driver: bridge
  
