services:
  # Servicios de LOCUST
  master:
    image: locustio/locust
    networks:
      - kuber-net
    ports:
      - "8089:8089"
    volumes:
      - ./Backend/Locust/locustfile.py:/mnt/locust/locustfile.py  
    working_dir: /mnt/locust  # El directorio de trabajo es /mnt/locust
    command: -f /mnt/locust/locustfile.py --users 10 --master -H http://api_rust:8000

  
  worker:
    image: locustio/locust
    networks:
      - kuber-net
    volumes:
      - ./Backend/Locust/data:/mnt/locust/data  
      - ./Backend/Locust/locustfile.py:/mnt/locust/locustfile.py 
    working_dir: /mnt/locust  
    command: -f /mnt/locust/locustfile.py --worker --master-host master

  # API_rust
  api_rust:
    build: ./Backend/Rust/API
    ports:
      - "8000:8000"
    networks:
      - kuber-net

  # API_golang
  api_golang:
    build: ./Backend/Golang/API_gRPC
    environment:
      - API_PORT=8010
      - GRPC_SERVER_KAFKA=gRPC_kafka:50051
      - GRPC_SERVER_RABBITMQ=gRPC_rabbitmq:50052
    ports:
      - "8010:8010"
    networks:
      - kuber-net

  
  # server gRPC kafka
  grpc_kafka:
    build: ./Backend/Golang/gRPC_Servers/Kafka
    environment:
      # - KAFKA_BROKER=kafka:9092
      # - KAFKA_TOPIC=messages
      - GRPC_PORT=50051
    ports:
      - "50051:50051"
    networks:
      - kuber-net


  # server gRPC rabbitmq
  grpc_rabbitmq:
    build: ./Backend/Golang/gRPC_Servers/RabbitMQ
    environment:
      # - RABBITMQ_HOST=rabbitmq
      # - RABBITMQ_QUEUE=messages
      - GRPC_PORT=50052
    ports:
      - "50052:50052"
    networks:
      - kuber-net
    
    
networks:
  kuber-net:
    driver: bridge
  
